<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR97pbps\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR97pbps/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerR97pbps.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerR97pbps\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerR97pbps\EccubeProdProjectContainer([
    'container.build_hash' => 'R97pbps',
    'container.build_id' => '37c999b2',
    'container.build_time' => 1555322295,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR97pbps');
