<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLnkwpnw\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLnkwpnw/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLnkwpnw.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerLnkwpnw\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerLnkwpnw\EccubeProdProjectContainer([
    'container.build_hash' => 'Lnkwpnw',
    'container.build_id' => '5b7d4947',
    'container.build_time' => 1555316126,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLnkwpnw');
